/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Codeowners {
  constructor(excludedOwners?: Array<string> | undefined | null)
  static fromContent(content: string, excludedOwners?: Array<string> | undefined | null): Codeowners
  getOwners(path: string): Array<string>
}
